[versions]
# ------ project ------ #
compileSdk = "34"
targetSdk = "34"
minSdk = "33"
versionCode = "1"
versionName = "1.0"
agp = "8.5.2"
core-ktx = "1.9.0"
junit = "4.13.2"
androidx-test-ext-junit = "1.2.1"
espresso-core = "3.6.1"
lifecycle-runtime-ktx = "2.8.4"
activity-compose = "1.9.1"
navigation-compose = "2.7.3"
hilt-navigation-compose = "1.0.0"
compose-bom = "2023.03.00"
room = "2.5.0"
media3-exoplayer = "1.5.0"
glance = "1.0.0"
# ------ jetbrains ------ #
org-jetbrains-kotlin-android = "1.8.10"
org-jetbrains-dokka = "1.9.20"
# ------ google ------ #
com-google-gms-google-services = "4.4.2"
com-google-dagger-hilt = "2.48"
firebase-bom = "33.1.2"
# ------ google ------ #
coil = "2.4.0"

[plugins]
# ------ android ------ #
com-android-application = { id = "com.android.application", version.ref = "agp" }
com-android-library = { id = "com.android.library", version.ref = "agp" }
# ------ jetbrains ------ #
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin-android" }
org-jetbrains-dokka = { id = "org.jetbrains.dokka", version.ref = "org-jetbrains-dokka" }
# ------ google ------ #
com-google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "com-google-gms-google-services" }
com-google-dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "com-google-dagger-hilt" }

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle-runtime-ktx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
material3 = { group = "androidx.compose.material3", name = "material3" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3-exoplayer" }

glance = { group = "androidx.glance", name = "glance-appwidget", version.ref = "glance" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

# ------ google ------ #
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "com-google-dagger-hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "com-google-dagger-hilt" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-analytics-ktx = { group = "com.google.firebase", name = "firebase-analytics-ktx" }

# ------ coil ------ #
# TODO 他のやつもmoduleの記載に変えてしまっていいかも
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

[bundles]

